# install shellcheck  from https://github.com/koalaman/shellcheck
# run shellcheck
# fail build if shellcheck report anything bad

language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck

script:
    - shellcheck *.sh
